/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dreamhome;

import static dreamhome.CrudPropietario.st;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Eduardo
 */
public class ProcedureInfo extends javax.swing.JFrame
{
    DefaultTableModel model;
    /**
     * Creates new form ProcedureInfo
     */
    public ProcedureInfo()
    {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblProcedure = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePropi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProcedure.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProcedure.setText("Información propiedades");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMostrarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVolverActionPerformed(evt);
            }
        });

        tablePropi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String []
            {
                "Numero propiedad", "Estado", "Tipo", "Nombre propietario", "Nombre empleado"
            }
        ));
        jScrollPane2.setViewportView(tablePropi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblProcedure))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMostrar)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblProcedure)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrar)
                        .addGap(32, 32, 32)
                        .addComponent(btnVolver)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void listarInformacion() 
    {
        Connection cn = null;
        try 
        {
          // Parámetros de conexión
          String driver = "oracle.jdbc.OracleDriver";
          String url = "jdbc:oracle:thin:@localhost:1521:XE";
          String user = "user1";
          String pwd = "user1";
          // Conexión
          Class.forName(driver).newInstance();
          cn = DriverManager.getConnection(url, user, pwd);
          // Proceso
          String sql = "{call INFORMACIONCURSOR(?)}";
          CallableStatement cstm = cn.prepareCall(sql);
          cstm.registerOutParameter(1, OracleTypes.CURSOR);
          cstm.executeUpdate();
          ResultSet rs = (ResultSet) cstm.getObject(1);
          String [] titulos={"Numero propiedad","Estado","Tipo","Nombre propietario","Nombre empleado"};

            model= new DefaultTableModel(null,titulos);
            String []fila=new String[5];
            while(rs.next())
            {
                fila[0]=rs.getString("numero");
                fila[1]=rs.getString("estados");
                fila[2]=rs.getString("tipos");
                fila[3]=rs.getString("nombrepropie");
                fila[4]=rs.getString("nombreemple");
                model.addRow(fila);
            }
            tablePropi.setModel(model);
          rs.close();
          cstm.close();
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        } 
        finally
        {
          try 
          {
            cn.close();
          } 
          catch (Exception e) 
          {
          }
        }
    }
    
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarActionPerformed
    {//GEN-HEADEREND:event_btnMostrarActionPerformed
         listarInformacion();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVolverActionPerformed
    {//GEN-HEADEREND:event_btnVolverActionPerformed
        Home nhome = new Home();
        nhome.setVisible(true);
        ProcedureInfo.this.dispose();   
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ProcedureInfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ProcedureInfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ProcedureInfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ProcedureInfo.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ProcedureInfo().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblProcedure;
    private javax.swing.JTable tablePropi;
    // End of variables declaration//GEN-END:variables
}
